apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
  namespace: {{ .Values.global.namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service
  namespace: {{ .Values.global.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.services.user.serviceAccount.roleArn | quote }}
