apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: user-service-rollout
  namespace: {{ .Values.global.namespace }}
  labels:
    app: user-service-green
    app.kubernetes.io/part-of: shopsphere
spec:
  replicas: {{ .Values.services.user.replicas }}
  selector:
    matchLabels:
      app: user-service
      rollout: user-service-rollout
  strategy:
    blueGreen:
      activeService: user-service
      previewService: user-service-preview
      autoPromotionEnabled: false
      previewReplicaCount: 2
      scaleDownDelaySeconds: 30
  template:
    metadata:
      labels:
        app: user-service
        rollout: user-service-rollout
        app.kubernetes.io/part-of: shopsphere
    spec:
      serviceAccountName: user-service
      containers:
        - name: user-service
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.services.user.image.repository }}:{{ .Values.services.user.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: shopsphere-config
            - secretRef:
                name: shopsphere-secret
            - secretRef:
                name: shopsphere-db
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-preview
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/part-of: shopsphere
spec:
  type: ClusterIP
  selector:
    app: user-service-green
    rollout: user-service-rollout
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-green-active
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/part-of: shopsphere
spec:
  type: ClusterIP
  selector:
    app: user-service-green
    rollout: user-service-rollout
  ports:
    - name: http
      port: 8000
      targetPort: 8000
