apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app.kubernetes.io/part-of: shopsphere
  namespace: {{ .Values.global.namespace }}

spec:
  type: ClusterIP

  selector:
    app: user-service-green
    rollout: user-service-rollout

  ports:
    - name: http
      port: 8000
      targetPort: 8000
