services:

  jenkins:
    build:
      context: ./jenkins
    image: shopsphere-jenkins:1.1
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace/shopsphere
    networks:
      - shopsphere

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - shopsphere

  user-service:
    build:
      context: ./services/user-service
    image: shopsphere-user:1.0
    container_name: user-service
    ports:
      - "8001:8000"
    networks:
      - shopsphere

  product-service:
    build:
      context: ./services/product-service
    image: shopsphere-product:1.0
    container_name: product-service
    ports:
      - "8002:8000"
    networks:
      - shopsphere

  payment-service:
    build:
      context: ./services/payment-service
    image: shopsphere-payment:1.0
    container_name: payment-service
    ports:
      - "8004:8000"
    networks:
      - shopsphere

  notification-service:
    build:
      context: ./services/notification-service
    image: shopsphere-notification:1.0
    container_name: notification-service
    ports:
      - "8005:8000"
    networks:
      - shopsphere

  order-service:
    build:
      context: ./services/order-service
    image: shopsphere-order:1.0
    container_name: order-service
    ports:
      - "8003:8000"
    environment:
      USER_SERVICE_URL: http://user-service:8000
      PRODUCT_SERVICE_URL: http://product-service:8000
      PAYMENT_SERVICE_URL: http://payment-service:8000
    depends_on:
      - user-service
      - product-service
      - payment-service
    networks:
      - shopsphere

networks:
  shopsphere:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  jenkins_home:
