apiVersion: v1
kind: Secret
metadata:
  name: shopsphere-db
  namespace: shopsphere
type: Opaque
stringData:
  DB_HOST: "shopsphere-dev-postgres.cjos6ucqeepc.ap-south-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "shopsphere"
  DB_USER: "shopsphere_admin"
  DB_PASSWORD: "Heymanshu28"
