global:
  namespace: shopsphere

services:
  user:
    image:
      tag: "36"

  product:
    image:
      tag: "36"

  order:
    image:
      tag: "36"

  payment:
    image:
      tag: "36"

  notification:
    image:
      tag: "36"

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: true
